name: 'return-action'

inputs:
  test_property:
    required: false
    
outputs:
    return_info: 
      value: ${{ steps.return_info.outputs.action_fruit }}
      
runs:
  using: "composite"
  steps:
    - shell: bash
      id: return_info
      run: |
        echo "set output"
        echo "::set-output name=action_fruit::strawberry"
