name: 'return-action'

inputs:
  test_property:
    required: false
    
outputs:
    return_info: 
      value: ${{ steps.return_info.outputs.action_fruit }}
      
runs:
  using: "composite"
  steps:
    - shell: bash
      id: return_info
      run: |
        echo "set output"
        echo "action_fruit=Apple" >> $GITHUB_OUTPUT
        if [[ ${{ inputs.test_property }} == "yes" ]]; then
        echo "this is something" >> $GITHUB_STEP_SUMMARY
        echo "error_step=return-action" >> $GITHUB_OUTPUT
        echo "error_step_message=This is an error message" >> $GITHUB_OUTPUT
        exit 1
        fi
