name: 'return-action'

inputs:
  test_property:
    required: false
    
outputs:
    return_info: 
      value: ${{ steps.return_info.outputs.action_fruit }}
    error_step:
      value: ${{ steps.return_info.outputs.error_step || ''}}
    error_step_message:
      value: ${{ steps.return_info.outputs.error_step_message || ''}}
      
runs:
  using: "composite"
  steps:
    - shell: bash
      id: return_info
      run: |
        echo "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
        echo '${{ inputs.more_prop1 }}' | yq .[].name 
        echo "set output"
        echo "action_fruit=Apple" >> $GITHUB_OUTPUT

