name: App Exit Code Handling

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                run() {
                    go version
                    cd goapp
                    go build main.go
                    sudo chmod +x main            
                    ./main  
                }

                (run())
                echo "$?"
                
            - run: |
                echo here
