name: App Exit Code Handling

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |

                run() {
                    rc=$?
                    go build main.go
                    sudo chmod +x main            
                    ./main
                    exit $rc
                }

                go version
                cd goapp
                trap "run" EXIT  
                echo $?
                echo made it here

            - run: |
                echo here
