name: Not Your Bash

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        env:
            CUSTOMER: "customer1"
            ENVIRONMENT: "dev"
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo ${{ github.base_ref }}