name: baseRef

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo ${{ github.base_ref }}