name: testBool-to-env

on:
  workflow_dispatch:
    inputs:
      fixOperationInProgress:
        type: boolean
      fixCannotPatch:
        type: boolean

env:
  FIX_OPERATION_IN_PROGRESS: ${{ fromJSON('["", " --fixOperationInProgress"]')[github.event.inputs.fixOperationInProgress == 'true' && 1 || 0] }}${{ fromJSON('["", " --fixOperationInProgress"]')[github.event.client_payload.additonalProperties.fixOperationInProgress == 'true' && 1 || 0] }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Thing: *${FIX_OPERATION_IN_PROGRESS}*"
