name: Call-Action

on:
  workflow_dispatch:
    inputs:
      

jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/return-action
        with:
          test_property: "some test value"
    
