name: Caller Workflow (Uses reusable workflow)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yaml
        with:
          input: "mtintes"
