name: Caller Workflow (Uses reusable workflow)

on: workflow_dispatch

jobs:
  caller-job:
    permissions:
      contents: read
      pull-requests: write
    uses: mtintes/github-actions-examples/.github/workflows/reusable_workflow.yaml@main
    with:
      name: "mtintes"
