name: Call-Action outputs Summary

on:
  workflow_dispatch:
      

jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: action_id
        uses: ./.github/actions/return-action
        with:
          test_property: "yes"
      - run: echo some output ${{ steps.action_id.outputs.return_info }}
  on_fail:
    name: Did fail?
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is something else" > $GITHUB_STEP_SUMMARY
