name: Caller Workflow (Uses reusable workflow)
#Demonstrates how to use a reusable workflow

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Doing something"
  caller-job:
    permissions:
      contents: read
      pull-requests: write
    uses: mtintes/github-actions-examples/.github/workflows/reusable_workflow.yaml@main
    with:
      name: "mtintes"
