name: Call-Action

on:
  workflow_dispatch:
      

jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: action_id
        uses: ./.github/actions/return-action
        with:
          test_property: "some test value"
          more_prop1: |-
            - name: sfsdfsdfsd
              version: 13bce4
              sonarqube: https://sfsdfsdfsd
              github: https://sdfsdfdsfds
            - name: other
              version: v2.14
              sonarqube: https://sfsdfsdfsfsdf
              github: https://sdfdsf
      - run: echo some output ${{ steps.action_id.outputs.return_info }}
          
      
    
