name: Call-Action

on:
  workflow_dispatch:
      

jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: action_id
        uses: ./.github/actions/return-action
        with:
          test_property: "some test value"
          extra_property: "test"
      - run: echo some output ${{ steps.action_id.outputs.return_info }}
          
      
    
