name: concurrency-run

concurrency:
  group: "test"

on:
  workflow_dispatch:

jobs:
  hello-world:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          sleep 30
          echo "hello world"
