name: If Condition bt Jobs

on:
  workflow_dispatch:
      
env:
  pass_this: true
  
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest
    outputs:
      pass_this: ${{env.pass_this}}
      
    steps:
      - uses: actions/checkout@v4
      - run: echo "I'm doing nothing"
  
  NoRun:
    name: Don't run
    runs-on: ubuntu-latest
    needs: start
    if: ${{!needs.start.outputs.pass_this}}
    steps:
      - run: echo "I shouldn't run ${{needs.start.outputs.pass_this}}"
      
  YesRun:
    name: Do run
    runs-on: ubuntu-latest
    needs: start
    if: ${{needs.start.outputs.pass_this}}
    steps:
      - run: echo "I should run ${{needs.start.outputs.pass_this}}"
    
