name: empty json matrix 

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest
    outputs:
      pass_this: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        if: github.ref == 'meh'
      - id: set-matrix
        run: |
          env_matrix="[]"  
          echo $env_matrix
          echo "matrix={\"include\":$env_matrix}" >> $GITHUB_OUTPUT
          
  output-job:
    name: runs
    runs-on: ubuntu-latest
    needs: start
    if: ${{ needs.start.outputs.pass_this != '' }}
    strategy:
      matrix: ${{ fromJson(needs.start.outputs.pass_this) }}
    steps:
      - run: echo "I shouldn't run ${{needs.start.outputs.pass_this}}"
