name: experiments

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mtintes/github-actions-examples/experiment@main
      - run: echo "from workflow"
          
      
