name: experiments

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: action_id
        uses: mtintes/github-actions-examples/action/experiment@main
      - run: echo "from workflow"
          
      
