name: Call-Action

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: action_id
        uses: mtintes/github-action-global/actions/return-action@main
        with:
          test_property: "some test value"
      - run: echo some output ${{ steps.action_id.outputs.return_info }}
