name: fromJson

on:
  workflow_dispatch:
    inputs:
      test-json: 
        type: string
        required: true
      
jobs:
  start:
    name: "Pass to other job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ fromJson( inputs.test-json ) }}
