name: fail if not a tag version

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: github ref name
              run: |
                #if [ "${{ github.ref_name }}" == "main" ] || [ "${{ github.ref_name }}" == "master" ]; then
                #  echo "please run this action from a tag version"
                #  exit 1
                #fi
                
                echo ${GITHUB_REF#*/}
