name: fail if not a tag version

on:
    workflow_dispatch:
    
jobs:
    fail-message:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') != true
        steps:
          - name: Fail check
            echo "please run this action from a tag version"
            exit 1
    job1:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')        
        steps:
            - name: fail if main branch
              run: |
                if [ "${{ github.ref_name }}" == "main" ] || [ "${{ github.ref_name }}" == "master" ]; then
                  echo "please run this action from a tag version"
                  exit 1
                fi
                
                echo ${GITHUB_REF#*/}
