name: jobs and checkouts

on:
  workflow_dispatch:
      
jobs:
  job1:
    name: checkout and update a thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD
      - run: |
          echo ${{ github.run_id }} > somefile.txt
          git add somefile.txt
          git config --global user.name 'test'
          git config --global user.email 'email@users.noreply.github.com'
          git commit -am "test" -m "something new"

          git fetch 
          git rebase
          git push
      - run: git rev-parse HEAD
          
  job2:
    name: dont checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD
      - run: git pull
      - run: git rev-parse HEAD
      
