name: jobs and checkouts

on:
  workflow_dispatch:
      
jobs:
  job1:
    name: checkout stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD
  job2:
    name: dont checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD
      
