name: matrix specific instance

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest
    outputs:
      pass_this: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          env_matrix="[{\"name\":\"one\"},{\"name\":\"two\"},{\"name\":\"three\"}]"  
          echo $env_matrix
          echo "matrix={\"include\":$env_matrix}" >> $GITHUB_OUTPUT
          
  output-job:
    name: runs
    runs-on: ubuntu-latest
    needs: start
    if: ${{ !failure() }}
    strategy:
      matrix: ${{ fromJson(needs.start.outputs.pass_this) }}
    steps:
      - name: should run one
        if: ${{ matrix.name == "one" }}
        run: echo one
      
      - name: should run two
        if: ${{ matrix.name == "two" }}
        run: echo two
        
