name: matrix needs

on:
  workflow_dispatch:
      
jobs:       
  matrix-job:
    name: runs
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: [1, 2, 3]    
    steps:
      - run: echo version: ${{ matrix.version }}
      
   dependency-job:
    name: wait for matrix jobs
    runs-on: ubuntu-latest
    needs: matrix-job
    if: ${{ !failure() }}
    steps:
      - run: echo "success"
  
