name: multiple jobs/any failures

on:
  workflow_dispatch:
      
jobs:
  job1:
    name: pass - no error
    runs-on: ubuntu-latest
    outputs:
      had_issue: ${{ steps.set-bool.outputs.env_bool }}
    steps:
      - id: set-bool
        run: |
          # echo "env_bool='true'" >> $GITHUB_OUTPUT
          
  job2:
    name: fail with error
    runs-on: ubuntu-latest
    outputs:
      had_issue: ${{ steps.set-bool.outputs.env_bool }}
    steps:
      - id: set-bool
        run: |
          # echo "env_bool='true'" >> $GITHUB_OUTPUT

  job3:
    name: pass2 - no error
    runs-on: ubuntu-latest
    outputs:
      had_issue: ${{ steps.set-bool.outputs.env_bool }}
    steps:
      - id: set-bool
        run: |
          # echo "env_bool='true'" >> $GITHUB_OUTPUT

  try-run:
    name: turn on or off
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    # safest way as '' evaluates to false or if you hand in true/false those are both thruthy and you have to string compare.
    if: ${{ needs.*.outputs.had_issue != '' }}
    steps:
      - name: maybe runs
        run: echo ${{ needs.start.outputs.check_bool }}
      
        
