## THIS PATTERN DOES WORK BUT IS A LITTLE LENGTHY 
name: multi-job-step-failure

on:
  workflow_dispatch:
      
jobs:
  job1:
    name: failure
    runs-on: ubuntu-latest
    outputs:
      had_issue: ${{ steps.fail.outputs.env_bool }}
    steps:
      - id: fail
        run: |
          echo "env_bool=ya" >> $GITHUB_OUTPUT
          echo "fail"
          exit 1
  job2:
    name: pass
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - id: fail
        run: |
          echo "Hi"
       
  try-run:
    name: turn on or off
    runs-on: ubuntu-latest
    needs: [job1, job2]
    # safest way as '' evaluates to false or if you hand in true/false those are both truthy and you have to string compare.
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: maybe runs
        run: |
          echo job1 ${{ needs.job1.result }}
          echo job1 step1 ${{ needs.job1.outputs.had_issue }}
          echo job2 ${{ needs.job2.result }}
  
