name: pass env bt jobs

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest
    outputs:
      pass_this: ${{ steps.set-env.outputs.somevar }}
    steps:
      - uses: actions/checkout@v2
      - id: set-env
        run: |
          env_var="Hi"  
          echo $env_var
          echo "somevar=$env_var" >> $GITHUB_OUTPUT
          
  output-job:
    name: runs
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: should run one
        run: echo ${{ needs.start.outputs.pass_this}}
      
        
