name: pass env bt jobs

on:
  workflow_dispatch:
      
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest
    outputs:
      pass_this: ${{ steps.set-env.outputs.somevar }}
      check_bool: ${{ steps.set-bool.outputs.env_bool }}
    steps:
      - uses: actions/checkout@v4
      - id: set-env
        run: |
          env_var="HI"  
          echo $env_var
          echo "somevar=$env_var" >> $GITHUB_OUTPUT
      - id: set-bool
        run: |
          # echo "env_bool='true'" >> $GITHUB_OUTPUT
          
  output-job:
    name: echo string
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: should echo "HI"
        run: echo ${{ needs.start.outputs.pass_this}}

  try-run:
    name: turn on or off
    runs-on: ubuntu-latest
    needs: start
    # safest way as '' evaluates to false or if you hand in true/false those are both thruthy and you have to string compare.
    if: ${{ needs.start.outputs.check_bool != '' }}
    steps:
      - name: maybe runs
        run: echo ${{ needs.start.outputs.check_bool }}
      
        
