name: secret exposure through action

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            exit_code: ${{ steps.do_something.outputs.failure_message }}
        steps:
          - uses: ./.github/actions/return-action
            with:
              some_secret: ${{ secrets.SOME_REAL_SECRET }}
