## THIS PATTERN DOES WORK BUT IS A LITTLE LENGTHY 
name: single-job-step-failure

on:
  workflow_dispatch:
      
jobs:
  job1:
    name: pass - no error
    runs-on: ubuntu-latest
    outputs:
      had_issue: ${{ steps.do-nothing.outputs.env_bool || steps.fail.outputs.env_bool }}
    steps:
      - id: do-nothing
        run: |
          # echo "env_bool='true'" >> $GITHUB_OUTPUT
      - id: fail
        run: |
          echo "env_bool='true'" >> $GITHUB_OUTPUT
          exit 1
          
  try-run:
    name: turn on or off
    runs-on: ubuntu-latest
    needs: [job1]
    # safest way as '' evaluates to false or if you hand in true/false those are both truthy and you have to string compare.
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: maybe runs
        run: |
          echo job1 ${{ needs.job1.outputs.had_issue }}
  
  output-debug:
    name: debug
    runs-on: ubuntu-latest
    needs: [job1]
    # safest way as '' evaluates to false or if you hand in true/false those are both truthy and you have to string compare.
    steps:
      - name: def runs
        run: |
          if [[ ${{ contains(needs.job1.outputs.had_issue, 'asdf') }} ]]; then
            echo yup
          fi
