name: Weird Job Conditions
#Tests out "if" conditional job conditions
#Subject to change a bit
on:
  workflow_dispatch:
    inputs:
      test1:
        description: true or false
      test2:
        description: true or false
        
env:
  pass_this: true
  
jobs:
  start:
    name: Pass to other job
    runs-on: ubuntu-latest 
    steps:
      - run: exit 1
  
  NoRun:
    name: Don't run
    runs-on: ubuntu-latest
    if: ${{ !failure() && (github.event.inputs.test1 == 'true' || github.event.inputs.test2 == 'true' )}}
    steps:
      - run: echo "I shouldn't run"
      
  YesRun:
    name: Do run
    runs-on: ubuntu-latest
    needs: start
    steps:
      - run: echo "I should run"
