name: what is output

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        id: value
        run: |
          reason_codes=$(jq -c --null-input '["ARGO_HEALTH_CHECK"]')
          reason_codes=$(jq -c '. | unique' <<< $reason_codes)
          echo $testValue
          echo "testOutputValue=$testValue" >> $GITHUB_OUTPUT
      - name: output
        run: |
          echo ${{ steps.value.outputs.testOutputValue }}
