name: what is output

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        id: value
        run: |
          reason_codes=$(jq --null-input '[ "ARGO_HEALTH_CHECK" ]')
          reason_codes=$(jq -rc '. | unique' <<< $reason_codes)
          echo $reason_codes
          echo "testOutputValue='$reason_codes'" >> $GITHUB_OUTPUT
          echo "newtest='[\"TEST\"]'" >> $GITHUB_OUTPUT
      - name: output
        run: |
          echo ${{ steps.value.outputs.testOutputValue }}
          echo ${{ steps.value.outputs.newtest}}
