name: what is output

on: workflow_dispatch

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        id: value
        run: |
          testValue="[ \"Test\" ]"
          echo $testValue
          echo "testOutputValue=$testValue" >> $GITHUB_OUTPUT
      - name: output
        run: |
          echo ${{ steps.value.outputs.testOutputValue }}
