name: What shell?

on:
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: 'shell version'
              run: |
                echo $SHELL
                $SHELL --version
                
